export const AUTH_SERVICE = 'AUTH_SERVICE';
export const SELLER_SERVICE = 'SELLER_SERVICE';
export const CATALOG_SERVICE = 'CATALOG_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
export const LOGISTICS_SERVICE = 'LOGISTICS_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
